github.com:
    users:
        sakshambhandakakar001-lgtm:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: sakshambhandakakar001-lgtm
